apiVersion: apps/v1
kind: Deployment
metadata:
  name: ericssonsics2-deploy-test
  labels:
    app: ericssonsics2-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ericssonsics2-test
  template:
    metadata:
      labels:
        app: ericssonsics2-test
    spec:
      containers:
      - name: ericssonsics2-test
        image: 136.225.131.250:5000/ericssonsics/5g-coral
       # command: ["/scripts/wrapper.sh"]
        command: ["/bin/bash"]
        args: ["-ec", "while :; do echo '.'; sleep 5 ; done"]
        ports:
        - name: porta
          protocol: TCP
          containerPort: 53001
        - name: portb
          protocol: UDP
          containerPort: 53002
       # volumeMounts:
       # - name: wrapper
       #   mountPath: /scripts
   #  volumes:
   #  - name: wrapper
   #    configMap:
   #      name: wrapper
   #      defaultMode: 0744

---

apiVersion: v1
kind: Service
metadata:
  name: ericssonsics2-service-test
 # namespace: ericssonsics1-namespace
  labels:
    app: ericssonsics2-service-test
spec:
  type: NodePort
  ports:
  - name: tcp-port
    port: 53001
    targetPort: 53001
    protocol: TCP
    nodePort: 30989
  - name: udp-port
    port: 53002
    targetPort: 53002
    protocol: UDP
    nodePort: 30981  
  selector:
    app: ericssonsics2-service-test   
