apiVersion: apps/v1
kind: Deployment
metadata:
  name: ericssonsics1-deploy
  labels:
    app: ericssonsics1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ericssonsics1
  template:
    metadata:
      labels:
        app: ericssonsics1
    spec:
      containers:
      - name: ericssonsics1
        image: 136.225.131.250:5000/ericssonsics/5g-coral
       # command: ["/scripts/wrapper.sh"]
        command: ["/bin/bash"]
        args: ["-ec", "while :; do echo '.'; sleep 5 ; done"]
        ports:
        - name: porta
          protocol: TCP
          containerPort: 53001
        - name: portb
          protocol: UDP
          containerPort: 53002
       # volumeMounts:
       # - name: wrapper
       #   mountPath: /scripts
   #  volumes:
   #  - name: wrapper
   #    configMap:
   #      name: wrapper
   #      defaultMode: 0744

---

apiVersion: v1
kind: Service
metadata:
  name: ericssonsics-service-test
  labels:
    app: ericssonsics-service-test
spec:
  selector:
    app: ericssonsics1
  type: NodePort
  ports:
  - nodePort: 31224
    port: 53001
    port: 53002


