apiVersion: apps/v1
kind: Deployment
metadata:
  name: sics-edge-test
  labels:
    app: sics-edge-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sics-edge-test
  template:
    metadata:
      labels:
        app: sics-edge-test
    spec:
      containers:
      - name: sics-edge-test
        image: 136.225.131.250:5000/ericssonsics/5g-coral
        resources:
          limits:
            cpu: "1"
          requests:
            cpu: "0.5"
       # command: ["/scripts/wrapper.sh"]
        command: ["/bin/bash"]
        args: ["-ec", "while :; do echo '.'; sleep 5 ; done"]
        securityContext:
          privileged: true
        ports:
        - name: porta
          protocol: TCP
          containerPort: 53001
       # - name: portb
        #  protocol: TCP
         # containerPort: 53002
        - name: portssh
          protocol: TCP
          containerPort: 22
       # volumeMounts:
       # - name: wrapper
       #   mountPath: /scripts
   #  volumes:
   #  - name: wrapper
   #    configMap:
   #      name: wrapper
   #      defaultMode: 0744
   
   
---

apiVersion: v1
kind: Service
metadata:
  name: sics-edge-test
 # namespace: sics-edge-namespace
  labels:
    app: sics-edge-test
spec:
  type: NodePort
  ports:
  - name: porta
    port: 53001
    targetPort: 53001
    protocol: TCP
    nodePort: 53001
#  - name: portb
#    port: 53002
#    targetPort: 53002
#    protocol: TCP
#    nodePort: 32102
  - name: portssh
    port: 22
    targetPort: 22
    protocol: TCP
    nodePort: 32122
  selector:
    app: sics-edge-test

